### ISSUE TITLE
Implement Pager.vue pagination into PrefixList.vue

### ISSUE THREAD

**Issue by Someguy123** [Privex/looking-glass#3]
Dependant on issue #2

We have the component [Pager.vue](https://github.com/Privex/looking-glass/blob/master/src/components/Pager.vue) already in the repository, which is a Vue component for pagination, however it isn't yet used.

[PrefixList.vue](https://github.com/Privex/looking-glass/blob/master/src/components/PrefixList.vue) should use Pager.vue for pagination, using the limit/skip GET parameters as explained in issue #2

**Comment by bt-cryptomancer** [comment]
Task complete in linked PR
